routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
//Route::get('home', function ()
//{
////    dd(\App\Models\Governorate::get());
//    return view('layouts.app');
//});


use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/hash',function (){
   return \Illuminate\Support\Facades\Hash::make('123456789');
});

Auth::routes();
Route::get('home', 'HomeController@index');
Route::Resource('governorate','GovernorateController');
Route::Resource('city','CityController');
Route::Resource('post','PostController');
Route::Resource('category','CategoryController');

Route::get('active/{id}' , 'ClientController@active');
Route::get('disactive/{id}' , 'ClientController@disactive');
Route::delete('delete{id}','ClientController@destroy');
Route::get('client','ClientController@client');
Route::get('setting','SettingController@index');
Route::Resource('contact','ContactController');
Route::get('getchangepassword','UserController@getChangePassword');
Route::post('changepassword','UserController@changePassword')->name('changepassword');
Route::Resource('role','RoleController');
Route::Resource('user','UserController');
Route::Resource('d-requests','DoRequestController');


//
//

Route::group(['middleware' => ['web'] ,'namespace' => 'client' , 'prefix' => 'blood_bank'], function () {
    Route::get('get_sign_up', 'WebController@signUp');
    Route::post('register', 'WebController@register');
    Route::get('get_login', 'WebController@login');
    Route::post('login', 'WebController@clientLogin');
    Route::get('home', 'WebController@index')->name('home');
    Route::get('contact_us', 'WebController@contactUs')->name('contactUs');
    Route::get('about_us', 'WebController@aboutUs')->name('aboutUs');
    Route::get('who_we_are', 'WebController@whoWeAre')->name('whoWeAre');
    Route::get('requests', 'WebController@requests')->name('requests');
    Route::get('logout', 'WebController@logout');

    Route::group(['middleware' => 'auth:client'], function () {
        Route::get('donate/{id}', 'WebController@donationDetails')->name('donate');
//        Route::get('donation_details', 'WebController@donationDetails')->('');
    });

});

//Route::get('/home', 'HomeController@index')->name('home');
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');
//
//Auth::routes();
//
//Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/menu.blade.php
<!-- sidebar menu: : style can be found in sidebar.less -->
<ul class="sidebar-menu" data-widget="tree">
    <li><a href="{{url('home')}}"><i class="fa fa-home"></i> الصفحه الرئيسيه</a></li>
    <li><a href="{{url(route('governorate.index'))}}"><i class="fa fa-flag"></i> المحافظات</a></li>
    <li><a href="{{url(route('city.index'))}}"><i class="fa fa-map"></i> المدن</a></li>
    <li><a href="{{url(route('category.index'))}}"><i class="fa fa-book"></i> الاقسام</a></li>
    <li><a href="{{url('post')}}"><i class="fa fa-clipboard"></i> المقالات</a></li>
    <li><a href="{{url('d-requests')}}"><i class="fa fa-medkit"></i> طلبات التبرع</a></li>
    <li><a href="{{url('client')}}"><i class="fa fa-phone"></i> العملاء</a></li>
    <li><a href="{{url('role')}}"><i class="fa fa-check-circle"></i> رتب المستخدمين</a></li>
    <li><a href="{{url('user')}}"><i class="fa fa-users"></i> المستخدمين</a></li>
    <li><a href="{{url('getchangepassword')}}"><i class="fa fa-key"></i> تغير كلمه المرور</a></li>
    <li><a href="{{url('contact')}}"><i class="fa fa-id-card"></i> تواصل معانا</a></li>
    <li><a href="{{url('setting')}}"><i class="fa fa-cogs"></i> الاعدادات</a></li>
</ul>